package schnorr_verify

import (
	"crypto/elliptic"
	"crypto/sha256"
	"math/big"
)

func fromHex(s string) *big.Int {
	if s == "" {
		return big.NewInt(0)
	}
	r, ok := new(big.Int).SetString(s, 16)
	if !ok {
		panic("invalid hex in source file: " + s)
	}
	return r
}

type CurveParams struct {
	// P is the prime used in the secp256k1 field.
	P *big.Int

	// N is the order of the secp256k1 curve group generated by the base point.
	N *big.Int

	// Gx and Gy are the x and y coordinate of the base point, respectively.
	Gx, Gy *big.Int

	// BitSize is the size of the underlying secp256k1 field in bits.
	BitSize int

	// H is the cofactor of the secp256k1 curve.
	H int

	// ByteSize is simply the bit size / 8 and is provided for convenience
	// since it is calculated repeatedly.
	ByteSize int
}

var curveParams = CurveParams{
	P:        fromHex("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"),
	N:        fromHex("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"),
	Gx:       fromHex("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),
	Gy:       fromHex("483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"),
	BitSize:  256,
	H:        1,
	ByteSize: 256 / 8,
}

func moduloReduce(k []byte) []byte {
	// Since the order of G is curve.N, we can use a much smaller number by
	// doing modulo curve.N
	if len(k) > curveParams.ByteSize {
		tmpK := new(big.Int).SetBytes(k)
		tmpK.Mod(tmpK, curveParams.N)
		return tmpK.Bytes()
	}

	return k
}

func jacobianToBigAffine(point *JacobianPoint) (*big.Int, *big.Int) {
	point.ToAffine()

	// Convert the field values for the now affine point to big.Ints.
	x3, y3 := new(big.Int), new(big.Int)
	x3.SetBytes(point.X.Bytes()[:])
	y3.SetBytes(point.Y.Bytes()[:])
	return x3, y3
}

func bigAffineToJacobian(x, y *big.Int, result *JacobianPoint) {
	result.X.SetByteSlice(x.Bytes())
	result.Y.SetByteSlice(y.Bytes())
	result.Z.SetInt(1)
}

type KoblitzCurve struct {
	*elliptic.CurveParams
}

func (curve *KoblitzCurve) ScalarBaseMult(k []byte) (*big.Int, *big.Int) {
	// Perform the multiplication and convert the Jacobian point back to affine
	// big.Ints.
	var kModN ModNScalar
	kModN.SetByteSlice(moduloReduce(k))
	var result JacobianPoint
	scalarBaseMultNonConstFast(&kModN, &result)
	return jacobianToBigAffine(&result)
}

func (curve *KoblitzCurve) ScalarMult(bx, by *big.Int, k []byte) (*big.Int, *big.Int) {
	// Convert the affine coordinates from big integers to Jacobian points,
	// do the multiplication in Jacobian projective space, and convert the
	// Jacobian point back to affine big.Ints.
	var kModN ModNScalar
	kModN.SetByteSlice(moduloReduce(k))
	var point, result JacobianPoint
	bigAffineToJacobian(bx, by, &point)
	ScalarMultNonConst(&kModN, &point, &result)
	return jacobianToBigAffine(&result)
}

func (curve *KoblitzCurve) Add(x1, y1, x2, y2 *big.Int) (*big.Int, *big.Int) {
	// The point at infinity is the identity according to the group law for
	// elliptic curve cryptography.  Thus, ∞ + P = P and P + ∞ = P.
	if x1.Sign() == 0 && y1.Sign() == 0 {
		return x2, y2
	}
	if x2.Sign() == 0 && y2.Sign() == 0 {
		return x1, y1
	}

	// Convert the affine coordinates from big integers to Jacobian points,
	// do the point addition in Jacobian projective space, and convert the
	// Jacobian point back to affine big.Ints.
	var p1, p2, result JacobianPoint
	bigAffineToJacobian(x1, y1, &p1)
	bigAffineToJacobian(x2, y2, &p2)
	AddNonConst(&p1, &p2, &result)
	return jacobianToBigAffine(&result)
}

var secp256k1 = &KoblitzCurve{
	CurveParams: &elliptic.CurveParams{
		P:       curveParams.P,
		N:       curveParams.N,
		B:       fromHex("0000000000000000000000000000000000000000000000000000000000000007"),
		Gx:      curveParams.Gx,
		Gy:      curveParams.Gy,
		BitSize: curveParams.BitSize,
		Name:    "secp256k1",
	},
}

// BIP-340 tag for the challenge hash
// var challengeTag = []byte("BIP0340/challenge")

func taggedHash(tag string, data []byte) []byte {
	tagHash := sha256.Sum256([]byte(tag))
	h := sha256.New()
	h.Write(tagHash[:])
	h.Write(tagHash[:])
	h.Write(data)
	return h.Sum(nil)
}

// VerifyBIP340 takes a 32-byte x-only pubkey, a message, and a 64-byte signature.
func VerifyBIP340(pubKeyBytes, msg, sigBytes []byte) bool {
	if len(pubKeyBytes) != 32 || len(sigBytes) != 64 {
		return false
	}

	// curve := btcec.S256()
	curve := secp256k1

	// 1. Parse r and s
	rBytes := sigBytes[:32]
	sBytes := sigBytes[32:]
	r := new(big.Int).SetBytes(rBytes)
	s := new(big.Int).SetBytes(sBytes)

	// Fail if r >= p or s >= n
	if r.Cmp(curve.P) >= 0 || s.Cmp(curve.N) >= 0 {
		return false
	}

	// 2. Lift X to get the Public Key Point (BIP-340 assumes even Y)
	// Prepending 0x02 treats it as a standard compressed pubkey with an even Y coordinate.
	pkBytes := make([]byte, 33)
	pkBytes[0] = 0x02
	copy(pkBytes[1:], pubKeyBytes)
	pubKey, err := ParsePubKey(pkBytes)
	if err != nil {
		return false
	}

	// 3. Calculate challenge e = hashBIP0340/challenge( r || pubKeyX || msg ) mod n
	var buf []byte
	buf = append(buf, rBytes...)
	buf = append(buf, pubKeyBytes...)
	buf = append(buf, msg...)

	eBytes := taggedHash("BIP0340/challenge", buf)
	e := new(big.Int).SetBytes(eBytes)
	e.Mod(e, curve.N)

	// 4. Calculate R = s*G - e*P
	// To do subtraction, we negate e: e_neg = (n - e) mod n
	eNeg := new(big.Int).Sub(curve.N, e)

	// s*G
	sGx, sGy := curve.ScalarBaseMult(sBytes)

	// e_neg*P (which is -e*P)
	ePx, ePy := curve.ScalarMult(pubKey.X(), pubKey.Y(), eNeg.Bytes())

	// R = s*G + (-e*P)
	Rx, Ry := curve.Add(sGx, sGy, ePx, ePy)

	// 5. Fail if R is the point at infinity (Rx == 0 && Ry == 0)
	if Rx.Sign() == 0 && Ry.Sign() == 0 {
		return false
	}

	// 6. Fail if R's Y-coordinate is odd
	if Ry.Bit(0) == 1 {
		return false
	}

	// 7. Success if R's X-coordinate matches r
	return Rx.Cmp(r) == 0
}

// func main() {
// 	// 1. Generate a valid private key
// 	privKey, err := btcec.NewPrivateKey()
// 	if err != nil {
// 		log.Fatalf("Failed to generate private key: %v", err)
// 	}
// 	pubKey := privKey.PubKey()

// 	// BIP-340 uses 32-byte X-only pubkeys
// 	pubKeyBytes := schnorr.SerializePubKey(pubKey)

// 	// 2. Hash your payload first! (BIP-340 requires a 32-byte message)
// 	rawPayload := []byte("Hello, zero-dependency world!")
// 	msgHash := sha256.Sum256(rawPayload)

// 	// 3. Sign using the official, audited btcsuite implementation
// 	signature, err := schnorr.Sign(privKey, msgHash[:])
// 	if err != nil {
// 		log.Fatalf("Failed to sign: %v", err)
// 	}
// 	sigBytes := signature.Serialize() // Exactly 64 bytes

// 	fmt.Println("--- Test Vectors ---")
// 	fmt.Printf("Message Hash : %x\n", msgHash)
// 	fmt.Printf("Public Key   : %x\n", pubKeyBytes)
// 	fmt.Printf("Signature    : %x\n", sigBytes)
// 	fmt.Println("--------------------")

// 	// ---------------------------------------------------------
// 	// TEST 1: The Happy Path
// 	// ---------------------------------------------------------
// 	isValid := VerifyBIP340(pubKeyBytes, msgHash[:], sigBytes)
// 	fmt.Printf("[Test 1] Valid signature check:\t\t %v (Expected: true)\n", isValid)

// 	// ---------------------------------------------------------
// 	// TEST 2: Tamper with the Message
// 	// ---------------------------------------------------------
// 	badMsgHash := msgHash
// 	badMsgHash[0] ^= 0xFF // Flip bits in the first byte of the hash

// 	isBadMsgValid := VerifyBIP340(pubKeyBytes, badMsgHash[:], sigBytes)
// 	fmt.Printf("[Test 2] Tampered message check:\t %v (Expected: false)\n", isBadMsgValid)

// 	// ---------------------------------------------------------
// 	// TEST 3: Tamper with the Signature
// 	// ---------------------------------------------------------
// 	badSigBytes := make([]byte, 64)
// 	copy(badSigBytes, sigBytes)
// 	badSigBytes[31] ^= 0xFF // Flip bits in the 'r' value of the signature

// 	isBadSigValid := VerifyBIP340(pubKeyBytes, msgHash[:], badSigBytes)
// 	fmt.Printf("[Test 3] Tampered signature check:\t %v (Expected: false)\n", isBadSigValid)
// }
